### ISSUE TITLE
Wrong mine type

### ISSUE THREAD

**Issue by LovingMelody** [sammypanda/nixos-nook-desktop#1]
https://github.com/sammypanda/nixos-nook-desktop/blob/734e35a291fc39eb2ec06102b2a34a42bbf753a9/pkgs/nook-desktop/default.nix#L86
 This app shouldn’t open links for jitsi-meet

**Comment by sammypanda** [comment]
yus! i'll remove that, must have left it in from when i was using the electron version of Jitsi Meet as a reference for the quirks and things around how to build electron xD

Thank you!
